### ISSUE TITLE
Final 0 remains for some reason

### ISSUE THREAD

**Issue by ctrlcctrlv** [mrled/cistercianjs#3]
It is hard for me to explain exactly what this bug is so I made a video

https://user-images.githubusercontent.com/838783/104271385-cf871300-5468-11eb-937d-ab61cb957aa9.mp4

I pressed seven four times but don't get the number 7777

**Comment by mrled** [comment]
Interesting. In the browsers I use regularly (Firefox on macOS, WebKit/Safari on iOS), it does keep the leading zero at first, but once I type four 7 characters, it removes the leading zero. Unfortunately, your case on Android is worse, since it doesn't remove that leading zero at all. I think I need to improve my form validation code, but it turns out to be a lot more confusing than I thought.

What I think I need to do is handle the empty case differently. Instead of making the default text box contain a zero, I want to allow it to be empty, and show a message like "type a number" when it's empty, instead of showing a Cistercian character. However, I haven't figured out how to make that work correctly yet.

When I allow the `num` state to be undefined in React, which would allow deleting the zero, it gives me warnings about controlled components: "A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen." Except that this should happen in this case - I need a value that represents an empty text box.

I'll keep working on this. Thanks for the report.

**Comment by ctrlcctrlv** [comment]
Cool—obviously it's not a severe bug. That was Chrome on Android for what it's worth.

**Comment by mrled** [comment]
I've made some changes that I think should resolve this. However, I don't have an Android device to test with; would you mind testing again?

**Comment by ctrlcctrlv** [comment]
Yup you fixed it 😊
